# Discussion {#thesis-discussion}

- Limitations of 3C based methods
- Plasticity and dynamics of chromatin interactions
- Single cell resolution
- Functional mechanism
- Establishment of compartments / TADs / loops
- Regulation of compartments / TADs / loops


- Notes
    - Neo-TADs by tandem-duplication in evolution [@Franke2016]
    - A key component and driver for new gene function in evolution or 
    neo-functionalization can be the birth of new enhancers through acquisition 
    of transcription factor binding and subsequent novel regulatory 
    functions [@Long2016].
    - This data can be computationally integrated with one-dimensional measurements along the genome
and lead to exciting findings of higher order organisation. 
    - TADs are not only structural units of chromosomes, but also functional building blocks of genomes.

## Discussion paralog co-regulation in TADs

The association of gene expression with gene localizing in TADs is consistent with a recent computational study with the aim to separate the proportion of expression associated with genome organization from independent sources. A large fraction of expression can be attributed to positioning of genes in genome architecture and hihgly informative for TAD activity and organization [@Rennie2018].




## Discussion on TAD evolution
Follow up studes might experimentally support the functional importance of evolutionary conserved TADs.
A very recent study investigated the requirenment of ultra-conserved non-coding region containing enhancers by 
knock-out experiments in mice [@Dickel2018].
Knowck-out mice that lack individual or combination of enhancers were viable but showed strong neurological phenotypes.
Indicating that the remarkably strong sequence conservation likely results from fitness deficit that appear subtle in a laboratory setting [@Dickel2018].
This could be similar for targeted deletions of conserved TAD boundaries.

The increased expression conservation of genes within TADs is somewhat consistent with a very recent study, in which promoter and enhancer activity was measured in liver samples from 15 species [@Berthelot2017]. In this study gene expression conservation could best be explained by the number and conservation of surrounding enhancers and promoters.

<!-- Summary of whole wokr -->
In this thesis, I analysed the functions of TADs for gene regulation and 
highlight their stability in evolution as well as their consideration when 
analyzing genomic variations in patient genomes.
- Paralog genes as model for co-regulation in TADs
- enhancer sharing
- co-expression

<!-- Connectio to TAD evolution -->
As consequence of these association of TADs with co-regulation, enhancer sharing 
and co-expression, we hypothesized TADs provide regulatory environments 
for genes and therefore be conserved during evolution. More specifically, 
we asked whether genomic rearrangement between related species would more 
frequently occur at TAD boundaries. Furthermore, we hypothesized that disruption 
of TADs during evolution might be associated with changes of gene expression
programs between the species.

<!-- Connection from TAD-evolution to position effect -->
The analysis of genomic rearrangements between human and other species during evolution lead to the conclusion
that TADs are important regulatory building blocks of genomes. Indeed the changes of 
expression profiles are associated with the disruption of TADs during evolution. 
This might likely lead to severe disadvantages to the organism, as was observed for example in genetic diseases [@Ibn-Salem2014; @Lupianez2015] and cancers.
Therefore, we interpret the depletion of evolutionary rearrangements in TADs and the expression change associated with TAD disruption to be a consequence of selective pressure on TAD structure. 
Therefore selective pressure is likely to act on TAD structures.
While in neutral selection

- Relate to GRBs and CNE clusters [@Harmston2017; @Polychronopoulos2017]

<!-- Discussing loop prediction for association of variatns to disease target genes -->
The majority of disease-associated variants uncovered by genome-wide association studies (GWAS) reside in noncoding sequences. Many variants are located near cis-regulatory sequences and enhancers and could, therefore, contribute to pathogenesis by affecting transcription of specific genes [@Hindorff2009]. 
The ability to measure long-range chromatin interactions makes it possible to assign understand the role of non-coding variants by predicting its interacting target gene [@Smemo2014; @Visser2012]. 
This has been shown by measuring the interactions of promoters in 17 human primary hematopoietic cells types revealing more than 2,400 potential disease-associated genes liked to thousands of GWAS SNPs [@Javierre2016].
In another study, the noncoding variants associated with schizophrenia could be annotated using Hi-C contact maps from human cerebral cortex [@Won2016].

## Further directions
- Plasticity and dynamics of chromatin interactions
- Single cell resolution 
    - Single cell Hi-C studies: [@Nagano2017; @Stevens2017]
    - Computational modelling of single cells [@Sekelja2016].
- Functional mechanism
- Establishment of compartments / TADs / loops
- Regulation of compartment / TADs / loops


## Conclusions
Recent methodological advances in chromatin conformation capture experiments resulted in genome-wide contact maps of genomes. These data lead to many interesting insights in the folding structures of genomes.
One important discovery was that chromosomes fold locally into discreet genomic domains, called TADs. 

In this thesis, I showed that TADs are not only structural units of genomes, but that they are also functionally important for the correct regulation of gene expression. 
TADs represent regulatory environment that restrict the interaction landscape of enhancers.
Indeed, functionally related genes, such as paralogs, are co-regulated within TADs. 
During evolution, new genes can emerge by duplication and find established regulatory environments within TADs. Therefore, TADs represent productive nests for novel genes in evolution.
The functional important of TADs was further stressed by their stability during hundred million years of evolution. Indeed stable TADs are associated with conserved expression profiles of genes. 

Disruption of TADs by rearrangements is associated to changes of gene expression profiles during evolution as well as in genomes of subjects with developmental diseases. 
While these disruptions of TADs might be beneficial for an organism and lead to evolutionary leaps in some cases, I showed in disease genomes, that disruption of TADs can result in severe phenotypes like mental retardation. 
Therefore, the three-dimensonal folding structure of genomes, including TADs and enhancer-promoter interactions have to be considered for the interpretation of genomic variants of patient genomes.  

While constantly decreasing costs of sequencing will further enable the analysis of individual genomes in many genetic syndromes or cancers, it will be increasingly important to correctly interpret these variants within their functional genomic context. 
To this end, we need a deeper understanding of the functional role of genome folding including its dynamics between single cells as well as its changes in specific cell types and conditions. 
To integrate diverse types of functional data that is measured along the genomes with the chromatin folding patterns and their interplay, we need carefully designed computational models. 
This will address not only fundamental questions such as evolution of genomes, mechanisms of gene regulation in differentiation and development, but also solve practical problems such as the interpretation of genetic variants in disease genomes for better developments of diagnosis and treatments.

